### ISSUE TITLE
Can't Install from nuget.org

### ISSUE THREAD

**Issue by wasimjee** [langboost/libaxolotl-uwp#12]
PM> Install-Package libaxolotl-uwp
Attempting to resolve dependency 'curve25519-uwp (≥ 1.0.1)'.
Successfully installed 'curve25519-uwp 1.0.3'.
Successfully installed 'libaxolotl-uwp 1.0.0'.
Successfully uninstalled 'curve25519-uwp 1.0.3'.
Install failed. Rolling back...
Install-Package : Could not install package 'curve25519-uwp 1.0.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package
 does not contain any assembly references that are compatible with that framework. For more information, contact the package author.
At line:1 char:16
- Install-Package <<<<  libaxolotl-uwp
  - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by langboost** [comment]
See #13 for a solution. Feel free to submit a pull request.

**Comment by jeff-r-skillrev** [comment]
libaxolotl-uwp depends upon curve25519-uwp, which is a Windows Runtime component. As such, you cannot use this code in the classic .NET environment. It is only meant to be used in Universal Windows apps.
