### ISSUE TITLE
how to use it in c# .net Windows Application

### ISSUE THREAD

**Issue by wasimjee** [langboost/libaxolotl-uwp#13]
how to use it in c# .net Windows Application with framework 4.0
 please help

**Comment by langboost** [comment]
This is basically the same as #12 and shouldn't take too much work. As shown here (https://msdn.microsoft.com/en-us/library/gg597391(v=vs.110).aspx) PCL's should support both Windows Store as well as .NET for the desktop. You should be able to adjust the .nuspec file and the .bat file to store the DLL in the appropriate subfolder. Feel free to submit that as a pull request. If possible, please include a sample project that shows the NuGet package works as expected (similar to https://github.com/langboost/axolotl-sample-client).

**Comment by wasimjee** [comment]
Its unable to locate curve25519-uwp

**Comment by jeff-r-skillrev** [comment]
libaxolotl-uwp depends upon curve25519-uwp, which is a Windows Runtime component. As such, you cannot use this code in the classic .NET environment. It is only meant to be used in Universal Windows apps.
