### ISSUE TITLE
Help - How to implement

### ISSUE THREAD

**Issue by matgott** [langboost/libaxolotl-uwp#14]
Hi, i using .NET WhatsApp api for c#. The messages are encrypted, how to used this library for desencrypt that?

**Comment by jeff-r-skillrev** [comment]
Hi, take a look at this sample client. It's very basic, but it implements the encryption and decryption processes.  https://github.com/langboost/axolotl-sample-client

**Comment by matgott** [comment]
Thanks bro! Is not possible open the project, u know why?

**Comment by jeff-r-skillrev** [comment]
Open an issue on the sample client repository, and provide some specific information about what is failing. I'll take a look.

**Comment by jeff-r-skillrev** [comment]
Also, for others who might look at this issue, the Java code samples here are nearly same-same with the C# version (i.e. object names, parameters, etc almost always match). So, you can look there for inspiration.  https://open-whisper-systems.readme.io/
