### ISSUE TITLE
Signing large messages

### ISSUE THREAD

**Issue by smndtrl** [langboost/libaxolotl-uwp#2]
Signing message are capped at 256byte

if (msg_len > MAX_MSG_LEN) {
    memset(signature_out, 0, 64);
    return -1;
  }
in curve_sigs.cpp

**Comment by jeff-r-skillrev** [comment]
Thanks, good catch. I will compare the code of curve25519-java and this repository to ensure they are in sync.

**Comment by smndtrl** [comment]
It's one of two unit tests failing on me for libaxolotl-windows. Other then that i think it was the outOfOrder one. Maybe i have the time next week to get it working.

**Comment by jeff-r-skillrev** [comment]
The limitation of 256 bytes should be fixed by the latest code commit now. https://github.com/langboost/libaxolotl-windows/commit/8fb492923c56cbc617637f13421c3bfda766e014
