### ISSUE TITLE
How to make this independent with mono 3.5 Net version 

### ISSUE THREAD

**Issue by assegaf** [langboost/libaxolotl-uwp#6]
Hi I am interested on this library, 
but for someuser they wont able to follow the code since there is user like me who want it run under mono framework,

at first, must use own library libcurve like this,
https://github.com/hanswolff/curve25519

but I am not able to integrade it, since the code library curve25519 and curve25519-uwt seem totally different, any idea?

**Comment by jeff-r-skillrev** [comment]
Hello 

Yes, I would love to see two implementations supported. One in C# and one in C++/uwp (due to speed and better code auditing from the libsodium community).

Let me look at the other repository you provided below and I will share any tips or ideas. Have you contacted this author? Maybe they know how to do the same things with their library, but in a different way.

What do you plan to do with curve25519?

Also, Microsoft has promised to bring .net to Linux and Mac. So soon, this library might simply run as-is.

Regards,
Jeff

-----Original Message-----

**Comment by assegaf** [comment]
I see, c is about speed, some user prefer .net/java and even python because integration with another modules that already exist.
I am implementing something like textsecure by openwhisper to encrypt and decrypt message, as middleware (console mono program, light weight ), based on v3.5 net framework mono.
basically I just need to encrypt and decrypt string (with private key and public key), 

I find difficult to follow with mono since this use library that are designed to windows > 8, 
espesially proto-buf, seem integrated well with api.

my question is 
1. its possible to me to modify library without any library external like protobuf-net (its not Google protobuf anymore), 
2. Integrate with c#  https://github.com/hanswolff/curve25519

**Comment by jeff-r-skillrev** [comment]
Curve25519 has no dependency on protobuf. That comes into play at the libaxolotl level (which uses protobuf and curve25519-uwp). Curve25519 is just assymetric cryptography, sort of like PGP. But when paired with the book-keeping and protocol specifics of libaxolotl, it makes a forward-ratcheting awesome crypto library designed for the messaging environment. There's a good blog post about it's advantages over existing approaches to async mobile messaging on Whisper System's blog here:
https://whispersystems.org/blog/advanced-ratcheting/

In https://github.com/hanswolff/curve25519, it appears that ClampPrivateKeyInline is used to generate private keys (pass in 32 bytes of randomness, then it modifies a few bytes to make it curve25519 compliant, just the same as my library does). So, under the hood it's functionally same-same, more or less. Just match the pieces together.

I have no interest in mono. I do have interest in integrating a pure C# implementation side-by-side with this C++ implementation - all still focused on only supporting UWP. So, I would be willing to consider merging pull requests that do that. Still, feel free to fork this and maintain something specific to mono! This library should stay fairly frozen now that it's functional.

Also, just FYI, sometime in the next month or so, a full implementation of TextSecure for UWP might show up on GitHub. :) @smndtrl and I have been working on that. It also will be focused purely on UWP, and not mono. But it may prove valuable for providing your own mono implementation.

I hope that helps! Thanks for your interest. Keep me posted on what you decide to pursue, and maintain or close this issue appropriately.
